<!-- #######  THIS IS A COMMENT - Visible only in the source editor #########-->
<h1><span style="font-weight: 400;">Frequently Asked Questions [FAQ]</span></h1>
<h3><strong>What is DISKUSS?</strong></h3>
<p><span style="font-weight: 400;">DISKUSS is a Mobile application that connects you instantly with </span><span style="font-weight: 400;">a board-certified doctor, counsellor, and therapist whenever and wherever needed. DISKUSS</span><span style="font-weight: 400;"> allows you to schedule appointments or speak via Audio / Video Call or Ask any questions that you may have with the certified specialists that you choose.&nbsp;</span></p>
<p><span style="font-weight: 400;">DISKUSS could save the patients hours by not having to go to the doctor&rsquo;s clinic and provides Video Consultations with reputed and recognized experts from the comfort of your couch.&nbsp;</span></p>
<p><span style="font-weight: 400;">There is no wait time at DISKUSS, as the service operates 24x7 and you are connected to someone instantly.</span></p>
<p><span style="font-weight: 400;">DISKUSS makes expert consultation and advice available and affordable for all.&nbsp; DISKUSS is highly recommended because of the affordability and convenience it provides to get HELP instantly.</span></p>
<h3><strong>Are the Health Professionals licensed?</strong></h3>
<p><span style="font-weight: 400;">DISKUSS has an extensive network of licensed Health Professionals, who are experts in their own fields with a long history of experience. All Health Care Professionals have been carefully selected. DISKUSS Does not employ or have any professional or therapists or counsellors who are not fully licensed. All the credentials of each Health care Professional on DISKUSS are carefully vetted </span><span style="font-weight: 400;">verified and background-checked</span><span style="font-weight: 400;"> and once the Board at DISKUSS approves a Health care Professional only then is the person allowed to be onboard at DISKUSS.&nbsp;</span></p>
<h2><strong>Types of Health Professionals?</strong></h2>
<p><strong>Psychiatrist</strong><span style="font-weight: 400;"> - A Psychiatrist is a medical doctor (M.D. or D.O.) who specializes in preventing, diagnosing, and treating mental illness. A psychiatrist's training starts with four years of medical school and is followed by a one-year internship and at least three years of specialized training as a psychiatric resident. A psychiatrist is trained to differentiate mental health problems from other underlying medical conditions that could present with psychiatric symptoms. They also monitor the effects of mental illness on other physical conditions (such as problems with the heart or high blood pressure), and the effects of medicines on the body (such as weight, blood sugar, blood pressure, sleep, and kidney or liver functioning)</span></p>
<p><span style="font-weight: 400;">As a doctor, a psychiatrist is licensed to write prescriptions. Many mental disorders - such as depression, anxiety, ADHD, or bipolar disorder - can be treated effectively with specific drugs</span></p>
<p><strong>Psychologist</strong><span style="font-weight: 400;"> - A psychologist has a doctoral degree (PhD, PsyD, or EdD) in psychology, which is the study of the mind and behaviors. Graduate school provides a psychologist an education in evaluating and treating mental and emotional disorders. After completing graduate school, a clinical psychologist completes an internship that lasts two to three years and provides further training in treatment methods, psychological theory, and behavioral therapy.</span></p>
<p><span style="font-weight: 400;">Licensed psychologists are qualified to do counseling and psychotherapy, perform psychological testing, and provide treatment for mental disorders. They are not, though, medical doctors. That means that, psychologists cannot write prescriptions. Often a psychologist will work in association with a psychiatrist or other medical doctor who provides the medical treatment for mental illness while the psychologist provides the psychotherapy.</span></p>
<p><strong>Counsellor </strong><span style="font-weight: 400;">&ndash; </span><span style="font-weight: 400;">A person trained to give guidance on personal or psychological problems is a Counsellor. Counsellors work in confidential settings with individuals who are experiencing personal difficulties, to help them overcome their problems and to make appropriate changes to their lives. Counsellors listen to, empathise with, encourage and help to empower individuals. A Health counsellor needs a Master's Degree in Clinical / Counselling Psychology and then </span><span style="font-weight: 400;">post-graduation of an additional certifications and then hours of experience providing therapy under the supervision of someone licensed is the basic requisite.&nbsp;</span></p>
<p><strong>Therapist </strong><span style="font-weight: 400;">&ndash; </span><span style="font-weight: 400;">Is a licensed mental health professional who helps clients improve their lives, develop better cognitive and emotional skills, reduce symptoms of mental illness and cope with various challenges. Therapist is a person trained in methods of treating illnesses especially without the use of drugs or surgery.</span> <span style="font-weight: 400;">A Therapist needs a </span><span style="font-weight: 400;">Bachelor's degree and master's degree in fields of Psychology or Counseling and thereafter clinical experience, with an Experience of between 2,000 and 4,000 hours of supervised clinical experience</span></p>
<p><strong>Sexologists </strong><span style="font-weight: 400;">&ndash; A Sexologist has to complete the MBBS degree course and go for PG in medical with specialization in sexology. Sexology is the scientific study of human sexuality, including human sexual interests, behaviors, and functions. A sexologist is a person who studies human sexuality and sexual behaviour and has a doctoral level degree in the chosen subject. Sexologists can provide sex counselling or sex therapy. Sexologists educate people about how to lead satisfying, safe and fulfilling sex lives by specifically addressing the issues which may include psychological or physiological problems.</span></p>
<h2><strong>What is the refund policy?</strong></h2>
<p><span style="font-weight: 400;">DISKUSS is committed to offering the best possible experience. However If a person is not satisfied from the Health Care Professional who has given advise then a person can request for a session with a different Health Care Professional. Full refund is made into your DISKUSS Wallet for your dissatisfied Session only once. This refund can be used to seek Help with another Health Care Professional on DISKUSS platform.</span></p>
<p><span style="font-weight: 400;">Customer service reviews refunds on a case-by-case basis in conjunction with the Health Care Professional. Refunds are usually by way of refund or credit into DISKUSS Wallet for future service. Cash Refunds are not made.</span></p>
<h2><strong>What problems can be handled at DISKUSS?</strong></h2>
<p><span style="font-weight: 400;">DISKUSS is committed to help users with any of the undermentioned issue, this list is not complete and feel free to ask our Customer Support about any other specific issues that you might want to addresss:</span></p>
<p><strong>Addictions </strong><span style="font-weight: 400;">&ndash; Covering all aspects of Addictions like Alcohol &ndash; Drugs - Gambling &ndash; Sex</span></p>
<p><span style="font-weight: 400;">Guidelines, risks, damage with addiction or withdrawal depressions</span></p>
<p><strong>Anxiety</strong><span style="font-weight: 400;"> - Anxiety is extreme worry that interferes with our daily lives. Find out more about anxiety disorders, treatments, trauma, triggers and phobias</span></p>
<p><strong>Behavioural Conditions</strong><span style="font-weight: 400;"> - Autism spectrum disorders, disruptive behavior disorders and others</span></p>
<p><strong>Children </strong><span style="font-weight: 400;">- Development, behaviour, nutrition, activity, wellbeing, identity, health, safety and trauma</span></p>
<p><strong>Dementia</strong><span style="font-weight: 400;"> - Early signs, types, management and coping</span></p>
<p><strong>Depression</strong><span style="font-weight: 400;"> - Types, risks, management, seeking help and warning signs.</span></p>
<p><strong>Drugs</strong><span style="font-weight: 400;"> - Drug use, overdose, types of drugs, health effects of addiction and getting help</span></p>
<p><strong>Family Violence</strong><span style="font-weight: 400;"> - Perpetrators often make excuses for their violence, for example, blaming alcohol or stress related</span></p>
<p><strong>Healthy Ageing</strong><span style="font-weight: 400;"> - Stay Involved and Stay mentally active and Secrets to Healthy Ageing</span></p>
<p><strong>Healthy Eating</strong><span style="font-weight: 400;"> - Nutrition basics, life stages, food safety, diet and health conditions, nutritional advice and supplements</span></p>
<p><strong>Healthy Mind</strong><span style="font-weight: 400;"> - Mood, healthy thinking, body image, relaxation, relationships and getting help</span></p>
<p><strong>Healthy Thinking - </strong><span style="font-weight: 400;">Assertiveness * Exercise and mood * Generalized anxiety disorder * It's okay to feel sad * Negative emotions * Coping with stress * Suggestions for families in crisis * Self-harm and self-injury * Stress busters * Strong relationships * Strong health * Talking through problems * Wellbeing</span></p>
<p><strong>Keeping active</strong><span style="font-weight: 400;"> - Becoming physically active, safety, types of physical activity and exercise and health conditions</span></p>
<p><strong>Mental illness</strong><span style="font-weight: 400;"> - Mental illnesses may be caused by life events, genetic factors or birth defects. Help is available to prevent or manage mental health problems.</span></p>
<p><strong>Pain and pain management</strong><span style="font-weight: 400;"> - Pain is our bodies built in alarm system. Learn about types of pain, what is acute, persistent or chronic pain and and how to manage your pain.</span></p>
<p><strong>Parenting</strong><span style="font-weight: 400;"> - Raising healthy children, child safety and support, maternal and child health</span></p>
<p><strong>Relationships</strong><span style="font-weight: 400;"> - Communication, family, work, separation and divorce, conflict, abuse and improving relationships</span></p>
<p><strong>Sexual health</strong><span style="font-weight: 400;"> - Safe sex, sexual identity, health conditions and sexuality, education, sexual abuse and sexual problems</span></p>
<p><strong>Sleep</strong><span style="font-weight: 400;"> - Conditions, risks and management</span></p>
<p><strong>Smoking and Tobacco</strong><span style="font-weight: 400;"> - Effects on your body, smoking-related conditions and quitting</span></p>
<p><strong>Stress </strong><span style="font-weight: 400;">- Signs of work-related stress can be physical, psychological and behavioural.</span></p>
<p><strong>Weight management</strong><span style="font-weight: 400;"> - Obesity and overweight, managing weight and healthy weight loss or gain</span></p>
<p><strong>Work</strong><span style="font-weight: 400;"> - Working life, stress, career change, risks, safety and workplace issues</span><br /><br /></p>